### ISSUE TITLE
Tumbleweeds!

### ISSUE THREAD

**Issue by trevorsg** [shieldsjared/tfs-extensions-misc#1]
I noticed this repo is quite empty! Let me know if I can help with anything!

**Comment by shieldsjared** [comment]
Ha! Thanks. Haven't had much time to devote to finalizing anything but I've been experimenting with a few things: (a) configurable Sonarqube summary widget, (b) a wiki through a facade (non developers find navigating through the code explorer to be confusing).... And (c) a reverse trace from test plan to query to see a map or code coverage against a selectable query.  but nevertheless, I've been using a local repo for the time being ;) I meant to delete this repo.
